package com.example.bankomatbackend.DataLoader;

public enum Huquqlar {
    ADDUSER,EDITUSER,DELETEUSER,READUSER,READMYMONEY,READBANKOMATMONEY,
    ADDCARD,DELETECARD,EDITCARD,READCARD,
    ADDLAVOZIM,EDITLAVOZIM,READLAVOZIM,DELETELAVOZIM,READALLLAVOZIM,
    ADDKOMISSIYA,EDITKOMISSIYA,DELETEKOMISSIYA,READKOMISSIYA,
    PULYECHISH,PULTOLDIRISH,PAROL,
    ADDBANK,EDITBANK,DELETEBANK,READBANK,
    ADDBANKOMAT,EDITBANKOMAT,DELETEBANKOMAT,READBANKOMAT

}
